### ISSUE TITLE
The package isn't signed. 

### ISSUE THREAD

**Issue by AshokAmirthalingam** [pathaksomesh06/MISA#1]
First and foremost, I would like to express my gratitude for developing the app, I truly appreciate your efforts. I understand that this is the first version of MISA. However, I would like to raise an issue: the package is not signed, which is causing installation issues via the GUI. Installation via the CLI works fine.

**Comment by pathaksomesh06** [comment]
Hi @AshokAmirthalingam , many thanks for your feedback. The app is now signed & notarized and a new release is published now.
